// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/312556ead6370d3aeed0d0c782aee9a501f228a6/jquery.sortelements/index.d.ts
interface JQuery {
    sortElements(comparator:Function, getSortable?:Function):JQuery;
}
